spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: spring.manager.api.misc.CustomPhysicalNamingStrategy
    open-in-view: false

  sql:
    init:
      mode: ALWAYS
      schema-locations:
        - classpath:sql/schema.sql

  profiles:
    active: test

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8000/realms/main}